stages:
    - publish
    - deploy
variables:
    TAG_LATEST: $REGISTRY/recraftopensource/$CI_COMMIT_REF_NAME:latest
    TAG_COMMIT: $REGISTRY/recraftopensource/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
publish:
    image: docker:latest
    stage: publish
    services:
        - docker:dind
    script:
        - docker build -t $TAG_COMMIT -t $TAG_LATEST .
        - docker login -u $DOCKER_USER -p $DOCKER_PS $REGISTRY
        - docker push $TAG_COMMIT
        - docker push $TAG_LATEST
    only:
        - master
deploy:
    image: alpine:latest
    stage: deploy
    tags:
        - deployment
    script:
        - chmod og= $ID_RSA
        - apk update && apk add openssh-client
        - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u $DOCKER_USER -p $DOCKER_PS $REGISTRY"
        - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $TAG_COMMIT"
        - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f recraftopensource || true"
        - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p 3001:80 --name recraftopensource $TAG_COMMIT"
    only:
        - master